apiVersion: v1
kind: Service
metadata:
  name: {{ include "lbapi.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- include "lbapi.labels" . | nindent 4 }}
  annotations:
    {{- include "lbapi.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "lbapi.selectorLabels" . | nindent 4 }}
